### ISSUE TITLE
Link Teams with AD Groups

### ISSUE THREAD

**Issue by asgreen21** [The-Vanderbilt-University/vuit-github-public-src#4]
Seems that after the move to SSO at the org level teams are no longer able to sync with ad groups. 
Looks to be a setting at the org level but I think we also need some config on the SSO side. 
https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-saml-single-sign-on-for-your-organization/managing-team-synchronization-for-your-organization#enabling-team-synchronization

**Comment by EricTaylorVU** [comment]
This has been fixed
